name: Generate snake animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate snake.svg in pink
        uses: Platane/snk/svg-only@v3.1.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=pink

      - name: Setup Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Push snake.svg to output branch
        run: |
          git fetch origin output || git checkout -b output
          git checkout output
          cp dist/snake.svg dist/snake.svg
          git add dist/snake.svg
          git commit -m "Update snake.svg [ci skip]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} output --force
