name: Generate snake animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate snake.svg in pink
        uses: Platane/snk/svg-only@v3.1.0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=pink

      - name: Setup Git for push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch origin output || git checkout -b output

      - name: Push snake.svg to the output branch
        run: |
          git checkout output || git checkout -b output
          mkdir -p dist
          cp dist/snake.svg dist/snake.svg
          git add dist/snake.svg
          git commit -m "Update snake.svg [ci skip]" || echo "No changes to commit"
          git push origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
